### ISSUE TITLE
使用rrvideo --input 的时候 提示没有此命令 这个问题怎么解决

### ISSUE THREAD

**Issue by yukunan** [rrweb-io/rrvideo#1]

**Comment by Yuyz0112** [comment]
已经执行了 `npm i -g rrvideo` 吗？

**Comment by yukunan** [comment]
是的 已经执行了

**Comment by Yuyz0112** [comment]
`npm i -g rrvideo` 这个的输出以及 `rrvideo --input` 之后的输出看一下？

**Comment by yukunan** [comment]
![image](https://user-images.githubusercontent.com/49779983/99332582-36e67380-28bb-11eb-9bab-b86d5a1eb958.png)

**Comment by yukunan** [comment]
![Snipaste_2020-11-17_10-03-45](https://user-images.githubusercontent.com/49779983/99336238-43b79700-28bc-11eb-921e-12ed1e74ed6e.png)

**Comment by yukunan** [comment]
![Snipaste_2020-11-17_10-20-01](https://user-images.githubusercontent.com/49779983/99338092-85e1d800-28be-11eb-8646-6476966acfe3.png)

**Comment by Yuyz0112** [comment]
手边没有 windows 的环境，不确定是不是 PATH 变量之类的问题？

参考 https://stackoverflow.com/a/24042936/14647054

**Comment by xyj404** [comment]
#4 can fix this problem. If you are urgent, you can change cli file self.

**Comment by Yuyz0112** [comment]
released in 0.2.0
