### ISSUE TITLE
Sometimes mistakes happen(pipe:: End of file)

### ISSUE THREAD

**Issue by xingxingdegit** [rrweb-io/rrvideo#11]
Hello, Would you like give me a help.

It show me successful but the file is not found.     ”pipe:: End of file”  in the show.

[www@bx-insurance-core-track-video5 ~]$ rrvideo --input /tmp/ideaproject/erwan/insurance-core/tmp/json/445244655857087457.json --output 123.mp4 --configStr '{"width":360,"height":764}'
ffmpeg version 2.8.15 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100

pipe:: End of file

Successfully transformed into "/home/www/123.mp4".

![image](https://user-images.githubusercontent.com/20982661/118225974-a9c25700-b4b8-11eb-8e2b-cd8324a8f86b.png)

**Comment by xingxingdegit** [comment]
the env:

![image](https://user-images.githubusercontent.com/20982661/118227547-4980e480-b4bb-11eb-944c-a377d2eba86b.png)

**Comment by yuezhenyu0208** [comment]
Have you solved this problem? I've got this problem, too
你解决了么，我也遇到这个问题了

**Comment by xingxingdegit** [comment]
没有解决， 开发那边有人说录得文件有问题， 后边我就不管了。
