### ISSUE TITLE
rrvideo  未找到命令

### ISSUE THREAD

**Issue by doweryouxia** [rrweb-io/rrvideo#3]
windows
![image](https://user-images.githubusercontent.com/9098782/99615341-37674180-2a56-11eb-9fe6-7eee2c110a7c.png)
Linux：
![image](https://user-images.githubusercontent.com/9098782/99615481-70071b00-2a56-11eb-94b1-c2b5c7777afc.png)

**Comment by xyj404** [comment]
#4 can fix this problem.

**Comment by Yuyz0112** [comment]
Please try 0.2.0
