### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by gxsnyyx** [rrweb-io/rrvideo#6]
执行rrvideo之后有报错信息，请问原因是什么
![image](https://user-images.githubusercontent.com/37402863/102300486-02380b80-3f90-11eb-9bfe-3d327ac9dc44.png)

**Comment by Yuyz0112** [comment]
看起来是个 bug，可以先尝试指定 --ouput 绕过

**Comment by gxsnyyx** [comment]
指定--output后已解决该问题，是否跟ffmpeg版本有关
